### ISSUE TITLE
Apiato call too slow Helloword or every page

### ISSUE THREAD

**Issue by mrandydung** [apiato/apiato#377] opened 2018-02-27 04:24 UTC
## Expected Behavior

Call fast page or API
## Actual Behavior

I used Docker, apiato version 7x .I have enable or disable cache file, but everything bad, i see it slow . 
Tried to use 
php artisan route:cache
php artisan optimize
enable ELOQUENT_QUERY_CACHE
But nothing ! 
I used from local.
What was the problem? 
  - Apiato Version: 7.x

https://imgur.com/a/3Idud

**Comment by johannesschobel** [comment] 2018-02-27 07:57
you may want to disable `debugbar` and the `profiler`. These packages are known to be very (!!!) slow and should not be used for production mode (but rather for developing)

**Comment by adcuz** [comment] 2018-03-06 11:00
This is not caused by Apiato. Docker on Mac is SLOW, and there is no official solution. The only workaround currently is docker-sync. Without it I get load times up to 15 seconds, with docker-sync it's fast.

**Comment by johannesschobel** [comment] 2018-03-06 14:21
i'll close this issue for now, as i strongly believe, that this is not an apiato related issue. I have just installed a plain apiato project (default project from this repository) on a normal apache server and requests are processed below 500ms

**Closed by johannesschobel** 2018-03-06 14:21 UTC

**Comment by llstarscreamll** [comment] 2018-03-25 02:09
Hi @johannesschobel, how to disable the `profiler`?

**Comment by johannesschobel** [comment] 2018-03-25 11:50
There should be a flag in the `.env` file.. not sure how it is called :) but you should find it ;)

Furthermore, there should be a Middleware that handles the profiler stuff, I believe..

**Comment by johannesschobel** [comment] 2018-03-26 09:25
Hey @llstarscreamll ,

sorry, i was on "vacation" during the weekend - so i had no computer with me to check the respective config flags.. The flag is called `DEBUGBAR_ENABLED` within the `.env` file.

Hope this helps!?
