### ISSUE TITLE
configs not loading from ship/configs

### ISSUE THREAD

**Issue by egbertmza** [apiato/apiato#565] opened 2020-05-04 12:41 UTC
### Description:
the cors.php and hashids.php is not loaded from app/ship/configs, i have to copy these files to the root configs to get it working

### Expected Behavior:
cors.php and hashids.php should load from app/ship/configs as this is the default location

### Versions:
- Apiato Version:9.0.0 (as per php artisan apiato)
- PHP Version: 7.4

**Comment by Mohammad-Alavi** [comment] 2020-05-06 04:37
I had the same problem but it went away by it's own after a few days and i unfortunately couldn't find the root cause. The only change i remember happened before the fix was me upgrading my homestead-box from 9.3 to 9.4. 😕

**Comment by Tirro** [comment] 2020-05-06 05:49
Duplicate of #562

**Comment by darkons** [comment] 2020-06-05 10:24
I had same related issues:

Warning: Ambiguous class resolution, "Fruitcake\Cors\CorsServiceProvider" and problem with another app/Ship composer.json packages.

I resolved using "composer update" twice instead "composer install". No removed dependencies and moved config files.

Very strange, but I think will be easy to solve for @Mahmoudz

**Comment by egbertmza** [comment] 2020-06-11 16:42
This is still a problem for me, I had to copy repository.php from ship/confogs to app/config because it was not applying my pagination settings.... does anyone have any ideas ?

**Comment by egbertmza** [comment] 2020-06-19 09:01
Ok i eventually figured it out. perhaps @Mahmoudz can elaborate and clarify why, but in the composer.json it seems the laravel auto discovery has been enabled again. in the current version on github the composer.json contains 
"laravel": {
      "dont-discover": []
    },

this effectively enables auto-discovery. in the apiato documentation itself it states: 

**Important Information**: Laravel 5.5 introduces an `auto-discovery` feature that lets you automatically register `ServiceProviders`.
Due to the nature and structure of Apiato applications, this features **is turned off**, because it messes up how `config` files are loaded
in apiato. This means, that you still need to **manually** register 3rd-party `ServiceProviders` in the `ServiceProvider` of a `Container`.

I changed the config back to 

"laravel": {
      "dont-discover": ["*"]
    },

and my problem was solved....

**Comment by Mohammad-Alavi** [comment] 2020-08-07 16:57
Related issues:
https://github.com/apiato/apiato/issues/562
https://github.com/apiato/apiato/issues/571
I closed those other issues and reopened this open because this one is the completest and with a temporarily solution until we fix it permanently.

**Comment by Mohammad-Alavi** [comment] 2020-08-07 17:36
Laravel package auto discovery was enabled in this commit bd468b8fdf3e6896325669936259072f8491c4a3 which in turn caused configs not loading by Apiato due to complications mentioned in [this](https://github.com/apiato/apiato/issues/565#issuecomment-646523122) comment.

**Comment by moslem-deris** [comment] 2020-10-17 22:20
@Mohammad-Alavi This problem seems to be solved and the auto discovery feature is off again! Why not closing the issue?

**Closed** 2021-03-29 00:53 UTC
Labels: Priority:Critical, Type:Bug
