### ISSUE TITLE
Generator not working with command line params

### ISSUE THREAD

**Issue by desertfoxmb** [apiato/apiato#325] opened 2017-12-04 20:36 UTC
## Expected Behavior
Use command line params as described to kick start generation process

## Actual Behavior
Error during creation. Works as expected without -c, -f command line parameters

n Filesystem.php line 41:

  File does not exist at path C:\projectpath\vendor\apiato\core\Generator/Stubs/actions/0.stub

## Steps to Reproduce the Problem
Run
php artisan apiato:generate:action -cContainer -fDoSomethingAction

## Specifications
  - Apiato Version: 2.2

**Comment by johannesschobel** [comment] 2017-12-04 20:41
Can you update to the latest version of apiato/apiato (I think this should be 7.3 - not sure about it though...) ?! This issue was fixed some times ago, I think..

**Comment by desertfoxmb** [comment] 2017-12-04 21:33
I just ran composer update this morning and that is when I started getting the error. I ran a composer show and this is what I show for Apiato. Not sure how to tell which release version I have.

C:\path>composer show
apiato/containers-installer           v1.0.1
apiato/core                           v2.2.0  Core package for Apiato.

**Comment by johannesschobel** [comment] 2017-12-05 06:32
and which command are you running that produces the described error? Maybe i can reproduce it..

**Comment by desertfoxmb** [comment] 2017-12-05 07:25
php artisan apiato:generate:action - cContainerName - fActionFilename

To be clear, when I mentioned changelog.md, that's on my machine. In github it says 7.2. Not sure if that's available for stable composer install yet.

**Comment by johannesschobel** [comment] 2017-12-05 07:31
ah, now i see it.. good catch.. i'll debug into this ;) thanks

**Comment by johannesschobel** [comment] 2017-12-05 07:39
@desertfoxmb : it looks like, the respective prompts to enter the data are not presented to the user.. can you confirm this on your machine?

**Comment by johannesschobel** [comment] 2017-12-05 07:46
Can you try calling it this way:

```bash
php artisan apiato:generate:action --container=Foo --file=BarAction
```
@desertfoxmb ...
I think, it might get confused with the `-c / -f` alias here... however, i call the `apiato:generate:action` command all the time from the `controller generator` like described above.. and this works for me..

**Comment by johannesschobel** [comment] 2017-12-05 08:13
ok.. i tend to remove the `-c` and `-f` alias, because thats what causes the problem...
I just ran it several times on my machine.. if i use `--container=Bla --file=FooAction` it works fine.. but if i switch to `-cBla -fFooAction` its only called sometimes.. weird?!

Maybe because we both run it on a windows machine?

**Comment by johannesschobel** [comment] 2017-12-05 08:25
Hey @desertfoxmb : can you please take a look at the mentioned PR here?

**Comment by Mahmoudz** [comment] 2017-12-05 16:07
Closed by #60

**Closed by Mahmoudz** 2017-12-05 16:07 UTC

**Comment by desertfoxmb** [comment] 2017-12-05 18:09
Thanks for taking a look. I'll switch to the other implementation when generating files. And yes, I'm also on a Windows machine.

**Comment by johannesschobel** [comment] 2017-12-05 18:42
No problem.. you're welcome ;) please use `--container` from now on
