### ISSUE TITLE
Fresh install of stable returning ValueObject not found error

### ISSUE THREAD

**Issue by ralphstodomingo** [apiato/apiato#334] opened 2017-12-11 08:04 UTC
## Expected Behavior

Fresh install of apiato should return no errors.

## Actual Behavior

An error page occurs, and checking laravel.log file contains this error:
```
[2017-12-11 07:55:56] local.ERROR: Class 'Apiato\Core\Abstracts\ValueObjects\ValueObject' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Class 'Apiato\\Core\\Abstracts\\ValueObjects\\ValueObject' not found at D:\\Projects\
apiato-test\\app\\Ship\\Parents\\ValueObjects\\ValueObject.php:13)
[stacktrace]
#0 {main}
"} 

```

## Steps to Reproduce the Problem

  1. `composer create-project apiato/apiato my-api`
  2. Follow the rest of the steps at the Installation Guide

## Specifications

  - Apiato Version:
Surprisingly, I pulled stable, but composer tells me `apiato/core` is loaded from `dev-master`.

**Comment by johannesschobel** [comment] 2017-12-11 09:27
Hey man,

this is most likely because of the update from this weekend. @Mahmoudz decided to rename `ValueObjects` to `Values` throughout the framework.

Can you take a look at your `vendor/apiato/core/...` and check, if you have the latest update on `apiato/core`, that reflect this change? Furthermore, maybe you can explicitly check out `apiato/core : dev-master`?

**Comment by ralphstodomingo** [comment] 2017-12-11 09:48
Decided to reinstall using dev-master, and everything works. Checked the previous install and core used `Values` while the `Ship\Parents` contained a reference to `ValueObject`.
Not really a problem for me anymore since I jumped to dev-master, but it is a potential drag for those who want to get started with Apiato.

**Comment by johannesschobel** [comment] 2017-12-11 09:58
ok, basically that is the problem right here.. Your application "stays" on the "old version" - but you use the new `dev-master apiato/core`, where `ValueObjects` were changed to `Values`.

If you use the `apiato 7.1 LTS` this should not be a problem for you..  However, if you like to use the latest version (and believe me - the new one is going to be even more awesome!!! 😀 ) you need to **manually** update your already existing apiato containers. In order to do so, please take a look at the docs - there is a "how to manually upgrade" guide.. 

I'm closing this issue for now - feel free to ask, if you have additional questions

**Closed by johannesschobel** 2017-12-11 09:58 UTC

**Comment by ralphstodomingo** [comment] 2017-12-11 10:00
So the stable version right now is intended to work that way?
I just followed the installation guide and that error occurred.

**Comment by Mahmoudz** [comment] 2017-12-11 17:02
@ralphstodomingo I mistakenly used `dev-master` on a stable release. I've fixed it now. Please merge the latest Apiato release (v7.3.2) into your project, run composer update and everything should work just fine. Kindly let me know if you need any help. Best,

**Comment by ralphstodomingo** [comment] 2017-12-12 05:54
Thanks for fixing this, @Mahmoudz! And I appreciate the work you're putting into Apiato, you and @johannesschobel. Thanks again!

**Comment by johannesschobel** [comment] 2017-12-12 06:01
Glad it solved your issue! You are welcome :)
Kind regards

**Comment by vituocgia** [comment] 2018-01-10 09:03
Hello 
I'm using the 2.2.* but the same error as reported above occurs. What's going on?

**Comment by johannesschobel** [comment] 2018-01-10 12:53
Apiato `7.2.*` (LTS Version) uses `ValueObjects`. In Apiato 7.3.* (current master branch) this was renamed to `Values` because of the above-mentioned reasons.

However, the `apiato 7.2.*` version requires `apiato/core 2.1.*`. If you are using the `core 2.2` you are **no longer on the LTS Version of apiato!**. You are mixing framework and core components!

**Comment by vituocgia** [comment] 2018-01-11 09:11
It's quite strange because I created a new project with 7.3.*. and then I run composer update -> Got that error?? I will re-check it, thanks for your reply

**Comment by in-asif-mulla** [comment] 2018-01-22 07:53
Still issue exists. After `composer update` I am getting "Class 'Apiato\Core\Abstracts\ValueObjects\ValueObject' not found". When checked directory "www\vendor\apiato\core\Abstracts", I could not locate "ValueObjects" directory.

**Comment by san4io** [comment] 2018-02-02 05:22
Error remains the same.

Steps to Reproduce the Problem
composer create-project apiato/apiato my-api

**Comment by Kyslik** [comment] 2018-02-02 08:41
When this happens your best option is to check out automated scripts how they do it in order to make tests pass, https://github.com/apiato/apiato/blob/master/.travis.yml

I bet that if you copy paste that shell command (without `if`-`fi`s you will get Apiato up and running).

**Comment by san4io** [comment] 2018-02-02 09:01
This problem happens only after composer update. If i don't update it, everything runs smooth.
