### ISSUE TITLE
hi , i try used apiato laravel project for use it as backend (using apis) i install project apiato and run it normally test web api running successfully but when i test any of api route return not found i don't know where is the problem i want to work it locally , i used windows 10 any one can help me please??

### ISSUE THREAD

**Issue by MarahNajjar** [apiato/apiato#541] opened 2020-04-02 11:41 UTC
### Versions:
- Apiato Version: #.#.#
- PHP Version: #.#.#

**Comment by Te7a-Houdini** [comment] 2020-04-07 18:47
duplicate of #542

**Closed by Te7a-Houdini** 2020-04-07 18:47 UTC
