### ISSUE TITLE
Hashed Id's returning hash of primary key when value is null

### ISSUE THREAD

**Issue by desertfoxmb** [apiato/apiato#317] opened 2017-11-21 08:35 UTC
## Expected Behavior
Return null for the attribute that is null

## Actual Behavior
Return hash of primary key when attribute is null

## Steps to Reproduce the Problem

  1. Create model with PrimaryKeyId, OtherIdToHash attributes
  2. In transformer for model, hash both PrimaryKeyId and OtherKeyId. See code below.
  3. Retrieve saved model where OtherKeyId is null. The transformer returns hash of the primary key

## Specifications
  - Apiato Version: 2.0.7

## Additional Details
Code in transformer
`   public function transform(MyModel $entity)
    {
        $response = [
            'object' => 'MyObject',
            'Id' => $entity->getHashedKey(),
            'OtherKeyId' => $entity->getHashedKey($entity->OtherKeyId),
        ];

        return $response;
    }`

Expected JSON:
`{
    "data": [
        {
            "object": "MyObject",
            "Id": "xbd95q89l87mlvng",
            "OtherKeyId": null,
         }
     ]
}
`
Actual JSON:
`{
    "data": [
        {
            "object": "MyObject",
            "Id": "xbd95q89l87mlvng",
            "OtherKeyId": "xbd95q89l87mlvng",
         }
     ]
}
`

**Comment by yalsicor** [comment] 2017-11-28 10:13
Hi desertfoxmb,

As far as I know, the getHashedKey accepts the name of the key as parameter.
Try:
`'OtherKeyId' => $entity->getHashedKey('OtherKeyId'),`

Yal

**Comment by johannesschobel** [comment] 2017-11-28 12:51
Hey there..

You need to pass in the `key` and **not** the `value`.
With
```
'OtherKeyId' => $entity->getHashedKey($entity->OtherKeyId),
```

you pass the `value` of `OtherKeyID` to the `getHashedKey()` method.
What you need to do, however, is call

```
'otherKeyId' => $entity->getHashedKey('otherKeyId'),
```

Cheers

**Comment by desertfoxmb** [comment] 2017-11-28 14:43
Ok. Because it worked properly for non-null values I expected it would work that way.

**Comment by johannesschobel** [comment] 2017-11-28 15:10
does the proposed solution 
```
$entry->getHasedKey('yourFieldName');
```
work for you?

**Comment by yalsicor** [comment] 2017-11-28 15:24
@johannesschobel That is what I thought as well. However, after testing it I discovered that is is indeed the value that needs to be passed. If the value is null, the primary key of the object is used. I did update my post accordingly.

does my solution work for you?

Yal

**Comment by johannesschobel** [comment] 2017-11-28 15:27
@yalsicor i only took a guess based on the method signature ;) and `key` was misleading in this case?!

@desertfoxmb : can you help if the other solution from @yalsicor works for you?

I will take a look at it this week and try to make the use more clear. maybe this is a bug?

**Comment by yalsicor** [comment] 2017-11-28 15:43
@johannesschobel Yes, key is misleading in this case, that got me as well in the first place.

I wonder what would be a good approach on this. Would actually changing it to passing the key break anything? If we want to pass the key and not the value, I can make a PR for that.

**Comment by johannesschobel** [comment] 2017-11-28 15:59
I will dive into this issue and try to work out a solution. Not sure yet, what's the best approach on this ;)

**Comment by desertfoxmb** [comment] 2017-11-29 01:34
Traveling and haven't yet been able to test. Should I do that? The conversation makes me think there will indeed be a code update.

**Comment by johannesschobel** [comment] 2017-11-29 08:05
i will take a look at it during this week or weekend.. the problem is, that this (might) be a breaking change - depending on how this function is used throughout the framework..

**Comment by yalsicor** [comment] 2017-11-29 12:01
The longer I think about it, the more I think it should work by key rather than value. Maybe @Mahmoudz can shed some light on how this was supposed to work?

Added a PR with my solution in the apiato/core repo.

Yal

**Comment by johannesschobel** [comment] 2017-11-29 12:27
i have already created a PR myself and tested it @yalsicor .. i am writing the docs and so on in order to merge it..

**Comment by johannesschobel** [comment] 2017-11-29 13:57
@desertfoxmb please run `composer update` to update to the latest `master` of `apiato/core`.

You can now call
```php
$entity->getHashedKey('customId');
```
where `$entity->customId` is used to create a hashed value. If `$entity->customId` is not available (or the value of it cannot be used to create a hash (e.g., if it is a string or `null` or whatever)) this returns `""` (empty string).

See the linked PR for more details

**Comment by johannesschobel** [comment] 2017-12-02 12:19
i've closed this issue for now.. kindly reply if you don't think this is solved yet

**Closed** 2017-12-02 12:18 UTC
